main_app/urls.py
from django.urls import path
from . import views
from .views import translate, about
# from userprofile.views import add_favs

urlpatterns = [
    # path('', views.home, name='home'),
    path('', views.HomeView.as_view(), name='home'),
    path('posts/', views.PostList.as_view(), name='index'),
    path('posts/create/', views.PostCreate.as_view(), name='posts_create'),
    path('posts/<int:pk>/', views.PostDetail.as_view(), name='posts_detail'),
    path('posts/<int:pk>/update/', views.PostUpdate.as_view(), name='posts_update'),
    path('posts/<int:pk>/delete/', views.PostDelete.as_view(), name='posts_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('posts/<int:post_id>/add_favs/<int:profile_id>/',views.add_favs, name='add_favs'),
    path('profiles/<int:pk>', views.ProfileDetail.as_view(), name='profile_detail'),
    path('profiles/<int:profile_id>/add_photo/', views.add_photo, name='add_photo'),
    path('translate/', translate, name='translate'),
    path('about/', about, name='about')
]

speakeasy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.utils import timezone
from django.contrib.auth.models import User


LANGUAGES = (
    ('ZH', '中文'),  # Mandarin Chinese
    ('ES', 'Español'),  # Spanish
    ('EN', 'English'),  # English
    ('HI', 'हिन्दी-उर्दू'),  # Hindi-Urdu
    ('AR', 'العربية'),  # Arabic
    ('BN', 'বাংলা'),  # Bengali
    ('PT', 'Português'),  # Portuguese
    ('RU', 'Русский'),  # Russian
    ('FR', 'Français'),  # French
    ('HE', 'עברית'),  # Hebrew
)


class Post(models.Model):
    phrase = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    country_of_origin = models.CharField(max_length=200)
    native_language = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('posts_detail', kwargs={'pk': self.id})

    def __str__(self):
        return f'{self.id}:{self.phrase[:10]}'


class Comment(models.Model):
    comment = models.TextField(max_length=500)
    date = models.DateField(default=timezone.now)
    language = models.CharField(
        max_length=20,
        choices=LANGUAGES,
        default=LANGUAGES[2][0],
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}:{self.comment[:10]}'

    class Meta:
        ordering = ['-date']

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from main_app.models import Post
# Create your models here.
LANGUAGES = (
    ('ZH', '中文'),  # Mandarin Chinese
    ('ES', 'Español'),  # Spanish
    ('EN', 'English'),  # English
    ('HI', 'हिन्दी-उर्दू'),  # Hindi-Urdu
    ('AR', 'العربية'),  # Arabic
    ('BN', 'বাংলা'),  # Bengali
    ('PT', 'Português'),  # Portuguese
    ('RU', 'Русский'),  # Russian
    ('FR', 'Français'),  # French
    ('HE', 'עברית'),  # Hebrew
)

COUNTRIES = (
    ('🇺🇸', 'United States'),
    ('🇨🇦', 'Canada'),
    ('🇲🇽', 'Mexico'),
    ('🇧🇷', 'Brazil'),
    ('🇦🇷', 'Argentina'),
    ('🇫🇷', 'France'),
    ('🇩🇪', 'Germany'),
    ('🇮🇹', 'Italy'),
    ('🇪🇸', 'Spain'),
    ('🇨🇳', 'China'),
    ('🇯🇵', 'Japan'),
    ('🇰🇷', 'South Korea'),
    ('🇮🇳', 'India'),
    ('🇦🇺', 'Australia'),
    ('🇳🇿', 'New Zealand'),
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    primary_language = models.CharField(
        max_length=20,
        choices=LANGUAGES,
        default=LANGUAGES[0][0]
    )
    flag = models.CharField(
        max_length=20,
        choices=COUNTRIES,
        default=COUNTRIES[2][0]
    )
    favorite_posts = models.ManyToManyField(
        Post, related_name='favorited_by', blank=True)

    def __str__(self):
        return f'{self.id}:{self.user.username}, {self.favorite_posts}'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Photo(models.Model):
    url = models.CharField(max_length=200)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for profile_id: {self.profile_id} @{self.url}'

main_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import Comment
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment', 'language']
        widgets = {
            'comment': forms.Textarea(attrs={'placeholder': 'Enter translation/feedback here...'}),
        }


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

main_app/views.py
import uuid
import boto3
import os
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, TemplateView
from .models import Post, User
from userprofile.models import Profile, Photo
from .forms import CommentForm, UserForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from googletrans import LANGUAGES, Translator


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['profile_id'] = self.request.user.profile.id
        return context


class PostList(ListView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['profile_id'] = self.request.user.profile.id
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['phrase', 'country_of_origin',
              'native_language']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['profile_id'] = self.request.user.profile.id
        return context

class PostDetail(LoginRequiredMixin, DetailView):
    model = Post
    user_model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_id'] = self.request.user.profile.id
        context['user'] = self.request.user
        context['form'] = CommentForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.object
            comment.user = request.user
            comment.save()
            return redirect('posts_detail', pk=self.object.pk)
        else:
            context = self.get_context_data(object=self.object)
            context['form'] = form
            return self.render_to_response(context)


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['phrase', 'country_of_origin', 'native_language']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['profile_id'] = self.request.user.profile.id
        return context


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['profile_id'] = self.request.user.profile.id
        return context


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


class ProfileDetail(LoginRequiredMixin, DetailView):
    model = Profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['profile_id'] = self.request.user.profile.id
        return context


def add_favs(request, profile_id, post_id):
    profile = Profile.objects.get(id=profile_id)
    post = Post.objects.get(id=post_id)
    profile.favorite_posts.add(post)
    profile.save()
    return redirect('home')



def add_photo(request, profile_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to profile_id or profile (if you have a profile)
            Photo.objects.create(url=url, profile_id=profile_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('profile_detail', pk=profile_id)


def translate(request):
    text = request.GET.get('text', '')
    if not text:
        return render(request, 'translate.html', {'languages': LANGUAGES})
    source = request.GET.get('source', 'auto')
    dest = request.GET.get('destination', 'en')
    translator = Translator()
    if source != 'auto':
        detected_language = None
    else:
        detected_language = translator.detect(text).lang
    translation = translator.translate(text, src=source, dest=dest)
    if not translation:
        translation = None
    source_language = LANGUAGES.get(source)
    destination_language = LANGUAGES.get(dest)
    return render(request, 'translate.html', {'languages': LANGUAGES, 'translation': translation, 'detected_language': detected_language, 'text': text, 'source_language': source_language, 'destination_language': destination_language})




def about(request):
    return render(request, 'about.html')

main_app/templates/userprofile/profile_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style-maria.css' %}">



    <title>Profile</title>
</head>

<body>
    <nav class="navbar sticky-top navbar-expand-lg bg-warning">

        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'posts_create' %}">Add A Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">View Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
        </div>
    </nav>
    <div class="container-profile">

        <div class="left-side">
            <h1>{{ profile.user.first_name }}'s Profile</h1>
            {% for photo in profile.photo_set.all %}
            <div>
                <img class="profile-img" src="{{photo.url}}" alt="Profile Photo">
            </div>

            {% empty %}
            <div>No Photos Uploaded</div>
            {% endfor %}

            <form action="{% url 'add_photo' profile.id %}" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <label for="photo-file" id="file-label">Choose a file</label>
                <input type="file" name="photo-file" id="photo-file"">
                <br><br>
                <button type=" submit" class="btn btn-info">Upload Photo</button>
            </form>
            <hr>
            <p id="primary-language">Primary Language: {{ profile.get_primary_language_display }}</p>
            <hr>
            <h3>About Me</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit voluptatibus voluptas incidunt
                nulla rerum, non obcaecati sunt ipsa ab consectetur. Inventore nihil exercitationem, necessitatibus nisi
                eius sed iure libero cum?</p>
        </div>
        <div class="right-side">
            <h2>Favorite Posts:</h2>
            {% if profile.favorite_posts.all %}
            {% for post in profile.favorite_posts.all %}
            <div id="card">
                <div id="card-body">
                    <p>{{ post.phrase }}</p>
                </div>

            </div>
            {% endfor %}
            {% else %}
            <div>No favorite posts yet.</div>
            {% endif %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
        </script>
</body>

</html>